spring.application.name=kis-quant-v1
spring.config.import=${KIS_ENV_IMPORT:optional:file:./p_env[.properties]}

kis.base-url=${KIS_BASE_URL_REAL:}
kis.app-key=${KIS_APP_KEY_REAL:}
kis.app-secret=${KIS_APP_SECRET_REAL:}
kis.account-number=${KIS_REAL_DOMESTIC_STOCK_CANO:}
kis.account-product-code=${KIS_REAL_DOMESTIC_STOCK_ACNT_PRDT_CD:}
kis.timeout=${KIS_TIMEOUT:5s}

order.allowed-symbol=${KIS_ALLOWED_SYMBOL:001510}
order.max-order-krw=${KIS_MAX_ORDER_KRW:30000}
order.fixed-order-quantity=${KIS_ORDER_QTY:1}
